name: ML Pipeline

on:
  push:
    branches: [ main ]

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Create directories
      run: mkdir -p data/raw models

    - name: Download dataset
      env:
        KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
        KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
      run: |
        pip install kaggle
        kaggle datasets download -d pavansubhasht/ibm-hr-analytics-attrition-dataset
        unzip ibm-hr-analytics-attrition-dataset.zip -d data/raw/

    - name: Run training
      run: python src/train.py